### ISSUE TITLE
 SmoothMeshLines2 division by zero messages

### ISSUE THREAD

**Issue by gmayo** [thliebig/CSXCAD#2]
I am using  openEMS_0.0.31_x64 with Octave3.6.4_gcc4.6.2 on a Windows 7 machine
I get warning: division by zero messages (and occasional crashes) with the following code:

%SmoothMeshLines2 bug
% I originally found the problem with the following array:
%mesh.x=[];
%mesh.x=[mesh.x -225.00000   -75.50000   -74.50000   -71.50000];
%mesh.x=[mesh.x  -70.50000   -65.75000   -64.75000   -58.00000];
%mesh.x=[mesh.x  -57.00000   -51.75000   -50.75000   -44.25000];
%mesh.x=[mesh.x  -43.25000    -3.50000    -2.50000    -0.50000];
%mesh.x=[mesh.x    0.50000     2.50000     3.50000    43.25000];
%mesh.x=[mesh.x   44.25000    50.75000    51.75000    57.00000];  
%mesh.x=[mesh.x   58.00000    64.75000    65.75000    70.50000];
%mesh.x=[mesh.x   71.50000    74.50000    75.50000   225.00000];
%mesh2.x= SmoothMeshLines2(mesh.x,40);

% but I can generate an error with as little as:
mesh.x=[-3.50000     -2.50000    -0.50000    0.50000];
mesh2.x= SmoothMeshLines2(mesh.x,40);

**Comment by thliebig** [comment]
This is very old, I will close it. But in general, yes the SmoothMeshLinesX algorithm are a bit fragile...
