### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jinxinyang** [thliebig/CSXCAD#20]
Interface Python failed to install. How to install it on platform Window10?
![image](https://user-images.githubusercontent.com/37427124/98610278-39c8ed80-232a-11eb-8ed1-5af4ccbcc496.png)

**Comment by thliebig** [comment]
The python interface is currently Linux only... The build process for Windows is just a pain... sorry

**Comment by thliebig** [comment]
Please check the latest doc: https://docs.openems.de/python/install.html#windows
