### ISSUE TITLE
The build doesn't link binaries with libhdf5.so

### ISSUE THREAD

**Issue by yurivict** [thliebig/CSXCAD#36]
CMakeLists.txt contains:
```
set(HDF5_INCLUDE_DIRS "${LOCALBASE}/include")
set(HDF5_LIBRARY_DIRS "${LOCALBASE}/lib")
```
instead of looking it up with pkgconfig.

In the end binaries aren't linked with libhdf5.so

**Comment by thliebig** [comment]
I'm not sure at all what you want to say with this... what pkgconfig?
Does the compile/build not work? Does running/loading CSXCAD not work???

**Comment by yurivict** [comment]
> I'm not sure at all what you want to say with this... what pkgconfig?

https://www.freedesktop.org/wiki/Software/pkg-config/

When the package installs .pc files, like hdf5 does, cmake should use pkgconfig to look up such package.

> Does the compile/build not work? Does running/loading CSXCAD not work???

I am talking about build inconsistencies caught by the ports framework, not about run-time problems.
It doesn't use HDF45 when it probably should.

**Comment by thliebig** [comment]
Sounds to me like you should contact the pkg-config team. I don't see how this is an CSXCAD or cmake issue???
For me CSXCAD is linked just fine and needs to be as well....

**Comment by yurivict** [comment]
CSXCAD should use the cmake macro to look up hdf5.
How is this the pkgconf team problem? This is a bug in CSXCAD that it doesn't use proper cmake macros.

**Comment by thliebig** [comment]
This exactly what CSXCAD's CMakeLists.txt is doing, I don't find the lines that you mention above? Where are they coming from?

**Comment by thliebig** [comment]
Here is a link to the 4 lines dealing with hdf5: https://github.com/thliebig/CSXCAD/blob/3861f2102aa9d13fbb0edb115fe446aeca6a0c13/CMakeLists.txt#L103-L110

**Comment by yurivict** [comment]
I apologize for not looking at port patches.

Someone added a patch to the port that replaced this line:
> find_package(HDF5 1.8 COMPONENTS C HL REQUIRED)

The problem was that CSXCAD fails to configure with hdf5-1.12 fails when find_package has this minimum requirement: 1.8

Removing 1.8 solves the problem.
